FROM python:3.13.2-slim

RUN apt-get update && \
    apt-get install -y librdkafka-dev gcc && \
    rm -rf /var/lib/apt/lists/*
    
# Install Poetry
RUN pip install uv

WORKDIR /app

# Copy Poetry files first
COPY pyproject.toml poetry.lock ./

# Install dependencies
RUN uv pip install --system -r pyproject.toml

# Copy the app files to the correct location
COPY app/* ./

# Expose port
EXPOSE 8000

# Launch directly with Python
CMD ["python", "api.py"]
