FROM python:3.13.2-slim

# Install Poetry
RUN pip install uv

WORKDIR /app

COPY app/ ./app/

# Copy Poetry files
COPY pyproject.toml poetry.lock ./

# Install dependencies
RUN uv pip install --system -r pyproject.toml

COPY . .

# Expose port
EXPOSE 8000

# Launch directly with Python
CMD ["python", "api.py"]